stages:
- name: compile
  steps:
  - runScriptConfig:
      image: wangzhenalex/maven-aliyun
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: spring-boot-web
      pushRemote: true
      registry: 127.0.0.1:34606
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./Kubernetes/deploy.yaml
timeout: 60
notification: {}
