apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-web
  template:
    metadata:
      labels:
        app: spring-boot-web
        track: stable
    spec:
      containers:
        - name: spring-boot-web
          image: spring-boot-web
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-web-svc
spec:
  type: NodePort
  selector:
    app: spring-boot-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080